name: AI Shorts Robot

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *"

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Spust robot
        run: python main.py
